In [1]:
import plotly

In [2]:
import pandas as pd
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

init_notebook_mode(connected = True)

In [3]:
dw = pd.read_csv("file csv/python_ dataset_superstore_simple.csv")

In [4]:
dw

,order_id,order_date,customer_id,segment,category,sub_category,sales,quantity,profit
0,CA-2016-152156,2016-11-08,CG-12520,Consumer,Furniture,Bookcases,261.9600,2,41.9136
1,CA-2016-152156,2016-11-08,CG-12520,Consumer,Furniture,Chairs,731.9400,3,219.5820
2,CA-2016-138688,2016-06-12,DV-13045,Corporate,Office Supplies,Labels,14.6200,2,6.8714
3,US-2015-108966,2015-10-11,SO-20335,Consumer,Furniture,Tables,957.5775,5,-383.0310
4,US-2015-108966,2015-10-11,SO-20335,Consumer,Office Supplies,Storage,22.3680,2,2.5164
...,...,...,...,...,...,...,...,...,...
9983,CA-2014-110422,2014-01-21,TB-21400,Consumer,Furniture,Furnishings,25.2480,3,4.1028
9984,CA-2017-121258,2017-02-26,DB-13060,Consumer,Furniture,Furnishings,91.9600,2,15.6332
9985,CA-2017-121258,2017-02-26,DB-13060,Consumer,Technology,Phones,258.5760,2,19.3932
9986,CA-2017-121258,2017-02-26,DB-13060,Consumer,Office Supplies,Paper,29.6000,4,13.3200
9987,CA-2017-119914,2017-05-04,CC-12220,Consumer,Office Supplies,Appliances,243.1600,2,72.9480